<?
require('index.html');
require('stroll.html');
require('1_floor.html');
require('2_floor.html');
require('3_floor.html');
require('4_floor.html');
require('5_floor.html');
require('6_floor.html');
require('7_floor.html');
?>
